cid: 2
fabric:
  accelerator: gpu
  devices:
    - 0
root_dir: ${oc.env:PWD}
model:
  name: lstm
  config:
    n_features: 24
    hidden_units: 12
    lr: 0.001
data:
  name: turbofan
  config:
    data_path: ${root_dir}/pybiscus-plugins/data/turbofan/turbofan.txt
    engines_train_list: [2]
    engines_val_list: [64]
    engines_test_list: [69]
    window: 20
    batch_size: 8
    num_workers: 0
server_address: localhost:22222
