root_dir: ${oc.env:PWD}
flower_server:
  listen_address: '[::1]:3333'
server_run:
  num_rounds: '10'
  clients_fit_local_epochs: '1'
  loggers:
  - name: rich
    config:
      empty_configuration: true
  reporting:
    basedir: ${root_dir}/experiments
    add_timestamp_in_path: true
    server_config_filename: config_server.yml
    save_on_train_end:
      filename: final_checkpoint.pt
server_compute_context:
  hardware:
    accelerator: auto
    devices: auto
  metrics_loggers:
  - name: tensorboard
    config:
      subdir: tensorboard
server_strategy:
  pipeline:
  - name: metricdiffcompute
    config:
      empty_configuration: true
  - name: timediffcompute
    config:
      empty_configuration: true
  - name: saveserverfitparams
    config:
      reporting_sub_dir: rounds
      server_aggregated_fit_parameters_file_name: server_aggregated_fit_parameters.npz
  strategy:
    name: fedavg
    config:
      fraction_fit: '1'
      fraction_evaluate: '1'
      min_fit_clients: '2'
      min_evaluate_clients: '2'
      min_available_clients: '2'
      accept_failures: true
      inplace: true
data:
  name: mnist
  config:
    # the server only evaluates, on the whole official test split
    test:
      dir: ${root_dir}/datasets/mnist/test/
      batch_size: 32
    num_workers: 0
model:
  name: mnist_cnn
  config:
    hidden: 128
    n_classes: 10
    lr: 0.001
