fabric:
  accelerator: gpu
  devices:
    - 0
root_dir: ${oc.env:PWD}
logger:
  subdir: /experiments/federated/test_1/
strategy:
  name: "fabric"
  config:
    min_fit_clients: 2
model:
  name: cifar
  config:
    input_shape: 3
    mid_shape: 6
    n_classes: 10
    lr: 0.001
data:
  name: cifar
  config:
    dir_train: None
    dir_val: None
    dir_test: ${root_dir}/datasets/global_test/
    batch_size: 32
watermark:
  name: simple_watermark
  hyperparams:
    lr: 1e-4
    epochs: 100
  data:
    name: trigger_cifar
    config:
      dir_trigger: ${root_dir}/datasets/CWAFFLE
server_adress: "[::]:22222"
num_rounds: 2
# save_on_train_end: true
# weights_path: ${root_dir}/experiments/federated/test_1/lightning_logs/version_48/checkpoint.pt
client_configs:
  - ${root_dir}/configs/cifar10_cnn/localhost/without_ssl/client_1.yml
  - ${root_dir}/configs/cifar10_cnn/localhost/without_ssl/client_2.yml

