root_dir: ${oc.env:PWD}
client_run:
  cid: '2'
  pre_train_val: false
client_compute_context:
  hardware:
    accelerator: auto
    devices: auto
model:
  name: cifar
  config:
    input_shape: '3'
    mid_shape: '6'
    n_classes: '10'
    lr: '0.001'
data:
  name: cifar
  config:
    dir_train: ${root_dir}/datasets/train/
    dir_val: ${root_dir}/datasets/val/
    dir_test: ${root_dir}/datasets/test/
    batch_size: '32'
    num_workers: '0'
flower_client:
  server_address: localhost:3333
