root_dir: ${oc.env:PWD}
flower_server:
  listen_address: '[::]:3333'
server_run:
  num_rounds: '10'
  loggers:
  - name: rich
    config:
      empty_configuration: true
  - name: webhook
    config:
      webhook_url: http://localhost:5555/webhook/logs
      logger_id: "\U0001F5A7"
  reporting:
    basedir: ${root_dir}/experiments
    add_timestamp_in_path: true
    server_config_filename: config_server.yml
    save_on_train_end:
      filename: final_checkpoint.pt
    onnx_export:
      filename: model.onnx
      opset: '13'
      post_validation: false
server_compute_context:
  hardware:
    accelerator: auto
    devices: auto
  metrics_loggers:
  - name: tensorboard
    config:
      subdir: tensorboard
  - name: webhook
    config:
      webhook_url: http://localhost:5555/webhook/metrics
      logger_id: "\U0001F5A7"
server_strategy:
  decorators:
  - name: metricdiffcompute
    config:
      empty_configuration: true
  - name: timediffcompute
    config:
      empty_configuration: true
  strategy:
    name: fedavg
    config:
      min_fit_clients: '2'
data:
  name: cifar
  config:
    dir_train: ${root_dir}/datasets/train/
    dir_val: ${root_dir}/datasets/val/
    dir_test: ${root_dir}/datasets/test/
    batch_size: '32'
    num_workers: '0'
model:
  name: cifar
  config:
    input_shape: '3'
    mid_shape: '6'
    n_classes: '10'
    lr: '0.001'
